from ctypes import *


class AATargetInfo(Structure):
    _fields_ = [
        ("bValid", c_bool),
        ("nAllyLot", c_int),
        ("nAELot", c_int),
        ("nOELot", c_int),
        ("nEWLot", c_int),
        ("nDLLot", c_int),
        ("nPlatformnIdentify", c_int),
        ("bNTS", c_bool),
        ("nPrecisionType", c_int),
        ("nIdentification", c_int),
        ("nOESAWorkState", c_int),
        ("nAESAWorkState", c_int),
        ("bAETarget", c_bool),
        ("bOETarget", c_bool),
        ("bEWTarget", c_bool),
        ("bDLTarget", c_bool),
        ("nJamDegree", c_int),
        ("nIdentify", c_int),
        ("nIdentifyResults", c_int),
        ("nIdentifyAttackResults", c_int),
        ("nFormationTypes", c_int),
        ("fTargetDistanceDF_m", c_float),
        ("fDisAlterRateDF_ms", c_float),
        ("fTargetAzimDF_rad", c_float),
        ("fTargetPitchDF_rad", c_float),
        ("fTargetAzimVelGDF_rads", c_float),
        ("fTargetPitchVelGDF_rads", c_float),
        ("fVnDF_ms", c_float),
        ("fVuDF_ms", c_float),
        ("fVeDF_ms", c_float),
        ("fAccNDF_ms2", c_float),
        ("fAccUDF_ms2", c_float),
        ("fAccEDF_ms2", c_float),
        ("fDisPrecisionDF_m", c_float),
        ("fDisRatePrecisionDF_ms", c_float),
        ("fAzimPrecisionBDF_mrad", c_float),
        ("fPitchPrecisionDF_mrad", c_float),
        ("fAzhimRatePcsnBDF_mrads", c_float),
        ("fPitchRatePcsnBDF_mrads", c_float),
        ("fVnPcsnDF_ms", c_float),
        ("fVePcsnDF_ms", c_float),
        ("fVuPcsnDF_ms", c_float),
        ("fAccelNPcsnDF_ms", c_float),
        ("fAccelEPcsnDF_ms", c_float),
        ("fAccelUPcsnDF_ms", c_float),
        ("fTrackAngleDF_rad", c_float),
        ("fEntranceAngleDF_rad", c_float),
        ("fTargetAltDF_m", c_float),
        ("fMachDF_M", c_float),
        ("fTargetAzimAE_rad", c_float),
        ("fTargetPitchAE_rad", c_float),
        ("fTargetDistanceAE_m", c_float),
        ("fRadialVelocityAE_ms", c_float),
        ("fDisAlterRateAE_ms", c_float),
        ("fVnAE_ms", c_float),
        ("fVuAE_ms", c_float),
        ("fVeAE_ms", c_float),
        ("fTrackAngleAE_rad", c_float),
        ("fEnterAngleAE_rad", c_float),
        ("fAltAE_m", c_float),
        ("fMachAE_M", c_float),
        ("fTargetAzimIR_rad", c_float),
        ("fTargetPitchIR_rad", c_float),
        ("fTargetGrayIR", c_float),
        ("nTargetDisIR", c_int),
        ("nDisPreciseIR", c_int),
        ("fTargetDisIR_m", c_float),
        ("fVnIR_ms", c_float),
        ("fVuIR_ms", c_float),
        ("fVeIR_ms", c_float),
        ("fTrackAngleIR_rad", c_float),
        ("fEntranceAngleIR_rad", c_float),
        ("fMachIR_M", c_float),
        ("fDisAlterRateIR_ms", c_float),
        ("fTargetAzimEW_rad", c_float),
        ("fTargetPitchEW_rad", c_float),
        ("fTargetDisEW_m", c_float),
        ("fLastingTimeDL_s", c_float),
        ("nCampDL", c_int),
        ("nFormationTypeDL", c_int),
        ("nAltDL_m", c_int),
        ("fHeading_rad", c_float),
        ("fRadialVelocityDL_kmh", c_float),
        ("fVnDL_kmh", c_float),
        ("fVuDL_kmh", c_float),
        ("fVeDL_kmh", c_float),
        ("fLonDL_rad", c_float),
        ("fLatDL_rad", c_float),
        ("fNorthPosDL_m", c_float),
        ("fEastPosDL_m", c_float),
    ]


class CommonInfo(Structure):
    _fields_ = [
        ("bValid", c_bool),
        ("bMainWpnState", c_bool),
        ("bAssWpnState", c_bool),
        ("nAAMMissileNum", c_int),
        ("nSAAMMissileNum", c_int),
        ("fFuelInPlane_kg", c_float),
    ]


class FireControlRDM(Structure):
    _fields_ = [
        ("bValid", c_bool),
        ("fRaero_km", c_float),
        ("fRopt_km", c_float),
        ("fRpi_km", c_float),
        ("fRtr_km", c_float),
        ("fRacue_km", c_float),
        ("fRmin_km", c_float),
        ("fRmax_km", c_float),
        ("fAFPole_km", c_float),
        ("fDMC_deg", c_float),
        ("fOperatingDotAzim_rad", c_float),
        ("fOperatingDotPitch_rad", c_float),
        ("fOperatingCirleDiameter_rad", c_float),
        ("fClimAgl_deg", c_float),
        ("fPreLanuchTime_s", c_float),
        ("fMPI", c_float),
        ("nAttackIndication", c_int),
    ]


class FireControlIRM(Structure):
    _fields_ = [
        ("bValid", c_bool),
        ("fRmax_km", c_float),
        ("fRmin_km", c_float),
        ("fRtr_km", c_float),
        ("fSeekerAzim_rad", c_float),
        ("fSeekerPitch_rad", c_float),
        ("fSeekerAzimP_rad", c_float),
        ("fSeekerPitchP_rad", c_float),
        ("nAttackIndication", c_int),
        ("bIsTracked", c_bool),
        ("bIsOverMaxOffAxisAgl", c_bool),
    ]


class MslProperty(Structure):
    _fields_ = [
        ("bValid", c_bool),
        ("nWeaponLot", c_int),
        ("nLoseTimeValid", c_int),
        ("nAFPoleALValid", c_int),
        ("nType", c_int),
        ("nSeekerState", c_int),
        ("nTargetLot", c_int),
        ("fMslAzim_rad", c_float),
        ("fMslPitch_rad", c_float),
        ("fMslDis_km", c_float),
        ("fHitPercentage", c_float),
        ("fAssFlagAzim_rad", c_float),
        ("fAssFlagPitch_rad", c_float),
        ("fSeekerOpen", c_float),
        ("fLoseTime_s", c_float),
        ("fAFPoleAL_km", c_float),
    ]


class FCMInfo(Structure):
    _fields_ = [
        ("bValid", c_bool),
        ("nLot", c_int),
        ("fTargetMach_M", c_float),
        ("fTargetAlt_m", c_float),
        ("fTargetDis_km", c_float),
        ("fDisAlterRate_ms", c_float),
        ("fEnterAngle_rad", c_float),
        ("sFCMRDM", FireControlRDM),
        ("sFCMIRM", FireControlIRM),
        ("nMslPropertyNum", c_int),
        ("sMslProperty", MslProperty * 6),
    ]


class StateInfo(Structure):
    _fields_ = [
        ("nAvionicsMode", c_int),
        ("nAEPowerByDL", c_int),
        ("nRadiateManager", c_int),
        ("bICNIPower", c_bool),
        ("bJIDSPower", c_bool),
        ("bEWSPower", c_bool),
        ("bAEPower", c_bool),
        ("bOEDEPower", c_bool),
        ("nAEWorkMode", c_int),
        ("bAEIsRadiate", c_bool),
        ("bIsHPECM", c_bool),
        ("bIsFireHPECM", c_bool),
        ("nAEOPState", c_int),
        ("nAEACMMode", c_int),
        ("bAETargetAbort", c_bool),
        ("bAESTAS", c_bool),
        ("bAESTT", c_bool),
        ("nAEAADisMeasure", c_int),
        ("nAESphereSelect", c_int),
        ("nAETargetVelThreshold", c_int),
        ("bAEFakeGuideSignal", c_bool),
        ("nAEAAScanLines", c_int),
        ("nAEAAScanScale", c_int),
        ("fAEScanCenterAzim_rad", c_float),
        ("fAEScanCenterPitch_rad", c_float),
        ("nEWWorkMode", c_int),
        ("bIsCanRadiate", c_bool),
        ("bHPECMAsk", c_bool),
        ("bHighPresure", c_bool),
        ("bLaunchBait", c_bool),
        ("bWarnMslNearing", c_bool),
        ("bWarnMslLaunched", c_bool),
        ("nLeftFrontRadiation", c_int),
        ("nRightFrontRadiation", c_int),
        ("nBackRadiation", c_int),
        ("nPJammProSelect", c_int),
        ("bIsProCanSelect", c_bool * 7),
        ("bFlame", c_bool * 3),
        ("bIsLeftValid", c_bool),
        ("nBaitLeftState", c_int),
        ("nBaitLeftLaunchState", c_int),
        ("bIsRightValid", c_bool),
        ("nBaitRightState", c_int),
        ("nBaitRightLaunchState", c_int),
        ("nOEDEWorkState", c_int),
        ("nOETrackMethod", c_int),
        ("nOELaserState", c_int),
        ("nOETrackingState", c_int),
        ("bOELaserRadiate", c_bool),
        ("nOEAzimScanRange", c_int),
        ("nOEPitchScanRange", c_int),
        ("nMainWpnType", c_int),
        ("nTargetAlloc", c_int * 3),
        ("nAllyLot", c_int),
        ("nRCSType", c_int),
        ("nRCSType_Auto", c_int),
        ("nChaffLeftNum", c_int),
        ("nFlameLeftNum", c_int),
        ("bActiveBaitDropAdvise", c_bool),
    ]


class AIMInfoBack(Structure):
    _fields_ = [
        ("bValid", c_bool),
        ("nDLRecvFlag", c_int),
        ("bTrackingFlag", c_bool),
        ("bSeekerHPFlag", c_bool),
        ("bDataLineState", c_bool),
        ("nWeaponLot", c_int),
        ("fVx", c_float),
        ("fVy", c_float),
        ("fVz", c_float),
        ("fXe", c_float),
        ("fYe", c_float),
        ("fZe", c_float),
        ("fMTDistance", c_float),
    ]


class TargetInList(Structure):
    _fields_ = [
        ("bTargetWpnTypeMatchValid", c_bool),
        ("bTargetTypeValid", c_bool),
        ("bTargetModelValid", c_bool),
        ("bTrackProbabilityValid", c_bool),
        ("bMPIValid", c_bool),
        ("bTargetDisAlterRateValid", c_bool),
        ("bTargetDisValid", c_bool),
        ("bTargetLotValid", c_bool),
        ("bTargetPrecisionContent", c_bool),
        ("nEnvelopeType", c_int),
        ("bRaeroValid", c_bool),
        ("bPoptValid", c_bool),
        ("bRpiValid", c_bool),
        ("bRtrValid", c_bool),
        ("bRacueValid", c_bool),
        ("bRminValid", c_bool),
        ("bRmaxValid", c_bool),
        ("bFourAttackRegionValid", c_bool),
        ("nLot", c_int),
        ("nDisPre", c_int),
        ("nTargetDisBookbindAndExtrapolateAttr", c_int),
        ("nTargetAttackParameter", c_int),
        ("nTargetWpnTypeMatch", c_int),
        ("nPreciseType", c_int),
        ("nPlatformnIdentify", c_int),
        ("fTrackProbability", c_float),
        ("fMPI", c_float),
        ("fTheoryRaero_km", c_float),
        ("fRopt_km", c_float),
        ("fRpi_km", c_float),
        ("fRacue_km", c_float),
        ("fRtr_km", c_float),
        ("fRmin_km", c_float),
        ("fRmax_km", c_float),
        ("fDisAlterRate", c_float),
        ("fDis", c_float),
        ("nDLTargetLot", c_int),
    ]


class TacticalManagerInfo(Structure):
    _fields_ = [
        ("nTargetInListNum", c_int),
        ("sTargetInListData", TargetInList * 8),
    ]


class FighterPara(Structure):
    _fields_ = [
        ("fRealAzimuth_rad_rad", c_float),
        ("fMagneticAzimuth_rad", c_float),
        ("fGroundSpeed_ms", c_float),
        ("fDriftAngle_rad", c_float),
        ("fHorizontalTrackAngle_rad", c_float),
        ("fWindSpeed_ms", c_float),
        ("fWindDirection", c_float),
        ("dLongtitude_rad", c_double),
        ("dLatitude_rad", c_double),
        ("fAltitude_m", c_float),
        ("fHeading_rad", c_float),
        ("fPitch_rad", c_float),
        ("fRoll_rad", c_float),
        ("fVn_ms", c_float),
        ("fVu_ms", c_float),
        ("fVe_ms", c_float),
        ("fAccN_ms2", c_float),
        ("fAccU_ms2", c_float),
        ("fAccE_ms2", c_float),
        ("fAbsAlt_m", c_float),
        ("fRadioAlt_m", c_float),
        ("fRealAirspeed_kmh", c_float),
        ("fCalibratedAlt_m", c_float),
        ("fMach_M", c_float),
        ("fCAS_kmh", c_float),
        ("fNormalAcc_g", c_float),
        ("fVTrackAngle_rad", c_float),
        ("fMaxAttackAngle_rad", c_float),
        ("fMinAttackAngle_rad", c_float),
        ("fMaxCAS_kmh", c_float),
        ("fMinCAS_kmh", c_float),
        ("fMaxMach_M", c_float),
        ("fMaxNormalOverload_g", c_float),
        ("fMinNormalOverload_g", c_float),
    ]


class AlarmInfo(Structure):
    _fields_ = [
        ("bValid", c_bool),
        ("nTargetType", c_int),
        ("nLot", c_int),
        ("nEWLot", c_int),
        ("bEWAdvise1", c_bool),
        ("bEWAdvise2", c_bool),
        ("bEWAdvise3", c_bool),
        ("bEWAdvise4", c_bool),
        ("bJamState1", c_bool),
        ("bJamState2", c_bool),
        ("bJamState3", c_bool),
        ("bJamState4", c_bool),
        ("fTargetRaero", c_float),
        ("fTargetRtr", c_float),
        ("nTargetEnvelopeType", c_int),
        ("nIdentify", c_int),
        ("nPlatformType", c_int),
        ("nWeaponType", c_int),
        ("bWarnMslNearing", c_bool),
        ("bWarnMslLaunched", c_bool),
        ("nIdentifyResults", c_int),
        ("fDis", c_float),
        ("fMisAzi", c_float),
    ]


class otherInfo(Structure):
    _fields_ = [
        ("bOver", c_bool),
        ("nEndReason", c_int),
        ("fAggregateScore", c_float),
        ("fReward", c_float),
        ("nAlarmNum", c_int),
        ("sAlarm", AlarmInfo * 10),
        ("nHitFighterWeaponLot", c_int),
        ("nHitTargetWeaponLot", c_int),
        ("dTimeStamp", c_double),
        ("iCmdIndex", c_short),
        ("iCmdID", c_ushort),
    ]


class AIData(Structure):
    _fields_ = [
        ("AATargetDataListNum", c_int),
        ("sAATargetData", AATargetInfo * 20),
        ("sSMSData", CommonInfo),
        ("sFCMData", FCMInfo),
        ("sStateData", StateInfo),
        ("nAIMInfoInfoNum", c_int),
        ("sAIMInfo", AIMInfoBack * 6),
        ("sAttackList", TacticalManagerInfo),
        ("sFighterPara", FighterPara),
        ("sOtherInfo", otherInfo),
    ]
